name: demo-pipeline-tekton
namespace: apps
version: {version}

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

container:
  image: {image}
  ports:
    - name: http
      protocol: TCP
      containerPort: 8080
  env:
    - name: APP_NAME
      value: demo-pipeline-tekton
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "300m"
      memory: "512Mi"
  liveness:
    failureThreshold: 3
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  readiness:
    failureThreshold: 3
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3

hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilization: 70

service:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080